### ISSUE TITLE
As a developer I want to set up a user management framework that i can use to create user endpoints

### ISSUE THREAD

**Issue by faroeq33** [AllYourGoods/team-do-minor#22]
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-8.0&tabs=visual-studio
https://learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-8.0
```[tasklist]
### Tasks
- [x] Create a Login endpoint
- [x] Create a Register endpoint
- [x] Create a Refresh token endpoint
- [x] Create a endpoint to update users
- [x] Create an endpoint incase of a forgotten password
```
