### ISSUE TITLE
As a user, I want to have a product tag end-point, so that I can perform Create, Read and Delete operations product tags

### ISSUE THREAD

**Issue by MT0993790** [AllYourGoods/team-do-minor#55]
```[tasklist]
### Tasks
- [ ] Create GET /productTag endpoint to retrieve all product tags.
- [ ] Create POST /productTag endpoint to add a new product tag.
- [ ] Create DELETE /productTag/{id} endpoint to delete a product by its ID.
```
